#!/bin/bash

# Deploy the Overcast Charts application on DigitalOcean.
# This script takes about 5 minutes to run.

###############################################################################

# Instructions:

# 1. Install Overcast:
#
#    npm -g install overcast
#
# 2. Add your DigitalOcean API credentials to $HOME/.overcast/variables.json:
#
#    {
#      "DIGITALOCEAN_CLIENT_ID": "YOUR_CLIENT_ID",
#      "DIGITALOCEAN_API_KEY": "YOUR_API_KEY"
#    }
#
# 3. Run this script from the terminal:
#
#    git clone git@github.com:andrewchilds/overcast-charts.git
#    overcast-charts/recipes/deploy-to-digitalocean
#
# 4. Wait for the script to finish. Write down the generated password for your application.
#
# 5. Go to your assigned IP address and enter "overcast" and the generated password to log in.

###############################################################################

# Configuration:

cluster="charts"
instance="charts.001"

# List droplet sizes with `overcast digitalocean sizes`
sizeSlug="512mb"

# List droplet regions with `overcast digitalocean regions`
regionSlug="nyc2"

###############################################################################

# You shouldn't have to edit anything below.

dirName=$(dirname "$0")

echo "Creating cluster \"$cluster\" if it does not already exist..."
overcast cluster create $cluster

echo "Creating instance \"$instance\" on DigitalOcean..."
overcast digitalocean create $instance --cluster $cluster --size-slug $sizeSlug \
  --region-slug $regionSlug --image-slug "ubuntu-12-04-x64"

$dirName/deploy-to-existing-ubuntu $instance
